apiVersion: apps/v1
kind: Deployment
metadata:
  name: sage-storage-loader
spec:
  selector:
    matchLabels:
      app: sage-storage-loader
  template:
    metadata:
      labels:
        app: sage-storage-loader
    spec:
      containers:
        - name: sage-storage-loader
          image: waggle/sage-storage-loader
          envFrom:
            - configMapRef:
                name: sage-storage-loader-config-env
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: home-dirs
